config/routes.rb
Finesse::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users
  
  resources :projects
  resources :tags, only: [:index, :show]
  resources :questions
  resources :subscribers
  resources :testimonials

  root "pages#index"

  get "pages/contact"
  get "pages/price"
  get "pages/images"
  get "pages/about"
  get "pages/beautyfication"
  get "pages/roofing"
  get "pages/metall"
  get "pages/fence"
  get "pages/finishing"
  get "pages/building"
  get "pages/heating"
  get "pages/water_supply"
  get "pages/sewerage"
  get "pages/electrician"
  get "pages/pools"
  get "pages/polymer_flooring"
  get "pages/epox_flooring"

  

end

app/models/project.rb
class Project < ActiveRecord::Base
	acts_as_taggable
	validates :title, presence: true
	validates :intro, presence: true
	validates :image, presence: true
 	mount_uploader :image, ImageUploader
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def show
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.save
    respond_with(@project)
  end

  def update
    @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :intro, :description, :image, :tag_list)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :intro %><br>
    <%= f.text_field :intro %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %><br>
  </div>
  <div class="field">
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<h2><%= link_to project.title, project_path(project) %></h2>
<div><%= render project.tags %></div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<section id="content" class="container clearfix">
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Intro</th>
      <th>Description</th>
      <th>Image</th>
      <th>Tag</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.intro %></td>
        <td><%= project.description %></td>
        <td><%= image_tag project.image_url(:thumb) %></td>
        <td><%= project.tag_list.to_s.titleize %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>
</section>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Intro:</strong>
  <%= @project.intro %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @project.image_url(:thumb) if @project.image? %>
</p>

<p>
  <strong>Tags:</strong>
  <%= render @project.tags %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>