config/routes.rb
Finesse::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users
  
  resources :projects
  resources :tags, only: [:index, :show]
  resources :questions
  resources :subscribers
  resources :testimonials

  root "pages#index"

  get "pages/contact"
  get "pages/price"
  get "pages/images"
  get "pages/about"
  get "pages/beautyfication"
  get "pages/roofing"
  get "pages/metall"
  get "pages/fence"
  get "pages/finishing"
  get "pages/building"
  get "pages/heating"
  get "pages/water_supply"
  get "pages/sewerage"
  get "pages/electrician"
  get "pages/pools"
  get "pages/polymer_flooring"
  get "pages/epox_flooring"

  

end

app/views/layouts/_footer.html.erb
<!-- begin footer -->
	<footer id="footer">
    	<div class="container">
            <!-- begin footer top -->
            <div id="footer-top">
                <div class="one-third">
                	<div class="widget">
                        <h3>О компании</h3>
                        <p>Строительная компания "Рубин" — является динамично развивающейся строительной компанией Самары и Самарской области, выполняющей полный спектр строительных работ.</p>
                        <p>Наша компания имеет большой опыт работы как с физическими лицами так и с муниципальными предприятиями города Самара.</p>
                    </div>
                </div>
               

                <div class="one-third">
                	<div class="widget twitter-widget">
                    	<h3>Последние твиты</h3>
                        <div class="tweet">
                            <ul>
                            <% TwitterApi.tweets.each do |t| %>
                                <li>
                                <%= twitter_text(t.text) %>
                                </li>
                            <% end %>
                            </ul>                     
                        </div>
                    </div>
                </div>
                
                <div class="one-third column-last">
                	<div class="widget contact-info">
                    	<h3>Контакты</h3>
                        <p class="address"><strong>Адрес:</strong> 443066, г. Самара, <br/>
                        ул. Советской Армии, 93, офис 9</p>
                        <p class="phone"><strong>Телефон:</strong> +7 (846) 205-60-88</p>
                        <p class="email"><strong>Email:</strong> <a href="mailto:ckrubin@yandex.ru">ckrubin@yandex.ru</a></p>
                        <div class="social-links">
                        	<h4>Следите за нами</h4>
                            <ul>
                            	<li class="twitter"><a href="https://twitter.com/OooCKRubin" title="Twitter" target="_blank">Twitter</a></li>
                                <li class="facebook"><a href="https://www.facebook.com/profile.php?id=100009533717436" title="Facebook" target="_blank">Facebook</a></li>
                                <li class="google"><a href="#" title="Google+" target="_blank">Google+</a></li>
                                <li class="instagramm"><a href="#" title="Instagramm" target="_blank">Instagramm</a></li>
                                <li class="vk"><a href="http://vk.com/ckrubin" title="В контакте" target="_blank">В контакте</a></li>
                                <li class="ok"><a href="http://ok.ru/profile/581715436348" title="Одноклассники" target="_blank">Одноклассники</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                
            </div>
            <!-- end footer top -->

            <!-- begin footer bottom -->
            <div id="footer-bottom">
            	<div class="left">
                	<p>Все права защищены &copy; 2015 СК "Рубин"</p>
                </div>
                <div id="right">
                <p>
                    <% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span> | 
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Войти', new_user_session_path %>
<% end %>
                </p>
                    
                </div>
            </div>
            <!-- end footer bottom -->
        </div>
	</footer>
	<!-- end footer -->
</div>
<!-- end container -->

app/views/layouts/_header.html.erb
<head>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

<!--[if IE 8]> <html class="ie8 no-js"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js"> <!--<![endif]-->
	<!-- begin meta -->
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=8, IE=9, IE=10">
	<meta name="description" content="The site of the building company BC 'Rubin'.">
	<meta name="keywords" content="CK Rubin Building Company Samara Russia">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- end meta -->

    <!-- begin CSS -->
    <%= stylesheet_link_tag "color.css" %>
    <!-- end CSS -->
	
</head>


<body>

<div id="wrap">
	<!-- begin header -->
    <header id="header" class="container">
        <!-- begin header top -->
        <section id="header-top" class="clearfix">
            <!-- begin header left -->
            <div class="one-half">


                <h1 id="logo"><%= link_to image_tag("logo.png", :alt => "СК Рубин"), root_path, :method => :get %></h1>
            </div>
            <!-- end header left -->
            
            <!-- begin header right -->
            <div class="one-half column-last">
                <!-- begin contact info -->
                <div class="contact-info">
                    <p class="phone">+7 (846) 205-60-88</p>
                    <p class="email"><a href="mailto:ckrubin@yandex.ru">ckrubin@yandex.ru</a></p>
                </div>
                <!-- end contact info -->
            </div>
            <!-- end header right -->
        </section>
        <!-- end header top -->
        
        <!-- begin navigation bar -->
        <section id="navbar" class="clearfix">
            <!-- begin navigation -->
            <nav id="nav">
                <ul id="navlist" class="clearfix">

                    <li><%= link_to "О НАС", pages_about_url %></li>

                    <li><a data-rel="submenu1">УСЛУГИ</a>
                        <ul id="submenu1" class="ddsubmenustyle">
                        <li><%= link_to "Полимерные полы", pages_polymer_flooring_url %>
                        <ul id="submenu1" class="ddsubmenustyle">
                        <li><%= link_to "Эпоксидные наливные полы", pages_epox_flooring_url %>
                        </li>
                        </ul>
                        </li>
                            <li><%= link_to "Благоустройство", pages_beautyfication_url %></li>
                            <li><%= link_to "Кровельные работы", pages_roofing_url %></li>
                            <li><%= link_to "Металлоконструкции", pages_metall_url %></li>
                            <li><%= link_to "Отделочные работы", pages_finishing_url %></li>
                            <li><%= link_to "Малоэтажное строительство", pages_building_url %></li>
                            <li><%= link_to "Отопление и водоснабжение", pages_heating_url %></li>
                            <li><%= link_to "Электромонтажные работы", pages_electrician_url %></li>
                            <li><%= link_to "Бассейны", pages_pools_url %></li>
                        </ul>
                    </li>

                    <li><%= link_to "ВЫПОЛНЕННЫЕ РАБОТЫ", pages_images_url %></li>

                    <li><%= link_to "ЦЕНЫ", pages_price_url %></li>

                    <li><%= link_to "КОНТАКТЫ", pages_contact_url %></li>

                </ul>
            </nav>
            <!-- end navigation -->
            
            <!-- begin search form -->
            <form id="search-form" method="get">
                <input id="s" type="text" name="s" placeholder="Поиск &hellip;" style="display: none;">
                <input id="search-submit" type="submit" name="search-submit" value="Search">
            </form>
            <!-- end search form -->
        </section>
        <!-- end navigation bar -->
        
    </header>
    <!-- end header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_include_tag "ddlevelsmenu" %>
    
    <script type="text/javascript">
        ddlevelsmenu.setup("nav", "topbar");
    </script>

<!--     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->

</head>
<body>

<%= render "layouts/header" %>

<%= yield %>

<%= render "layouts/footer" %>

</body>
</html>